server:
  port: 8080
spring:
  application:
    name: servicepricestest
  h2:
    console:
      enabled: true
      path: /h2-console
      show-sql: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      data-locations:
        - classpath*:db/data.sql
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
